#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication foamClearPolyMesh

runApplication blockMesh
cp -r 0.org 0

# Create STL file
#./cat_stl.sh droplet.ast plate.ast > system_mm.stl
#surfaceConvert -scale 0.001 system_mm.stl constant/triSurface/system.stl

#surfaceFeatureExtract

#snappyHexMesh -overwrite

runApplication setFields
runApplication `getApplication`
